### ISSUE TITLE
Error in Compiling Program

### ISSUE THREAD

**Issue by merlin123h** [Nikait/Quiescis#1]
Hi.
When compiling Server.cpp this error occurs. please guide me about compiling this .cpp file.
Thanks.

![g++](https://user-images.githubusercontent.com/67941449/94065574-32f91200-fda0-11ea-81fc-057cf212402e.JPG)

**Comment by Nikait** [comment]
Ok, thanks, I'll fix it soon

**Comment by Nikait** [comment]
_wmkdir is a function from winapi windows, and on windows it will compile without errors, for linux I will write a little differently

**Comment by Nikait** [comment]
Try again, I fixed the bugs and it compiled well on linux
